### ISSUE TITLE
Add Feature preview backend side

### ISSUE THREAD

**Issue by DrMabuse23** [DrMabuse23/yii2-sir-trevor-js#3]
add preview in Backend 

markdown to html maybe with frontend asset ?

**Comment by schmunk42** [comment]
I think there should be a server side rendering of the contents in HTML, otherwise it could get complicated to work with sir-trevor contents and SEO.

**Comment by DrMabuse23** [comment]
@schmunk42 What about Seo in Backend ? ......

**Comment by schmunk42** [comment]
Will review this today.
